* A category in math represents a function application.
  It is composed by the types of a functions body, alongside with the
  type of its arguments and results. When represented as a graph, a
  composition containing an arrow may describe a function of type D
  taking arguments of type A while results are of type B.

  D :: (A -> B)
  
  Graphically the arrow represents the function and the order of
  application.

* Function objects and argument objects are represented as types.

* Rules of definition

  All terms used by a definition have to be defined before.

* A process can't refer to its final result, using it in its own
  computation.

  A task "Give me the set of all sets" can't comprise these "Set of all set".
  That way Rusell's paradox is avoided.

* Types are composed by rules

* The type of a natural number relies on the notion of equality.
  Natural numbers are symbols standing for distinction of objects of a
  comparable type. The succession of these distincting provides order.
  
